name: Screenshot generation
on:
  push:
    branches: [ 'impossibletomatch' ]
  pull_request:
    branches: [ 'impossibletomatch' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: pwd && cd ./screenshot-wrapping/ && pwd && npm ci && node index.js
    - name: Upload screenshots
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: ./screenshot-wrapping/output/
